# -*- coding: utf-8 -*-
"""S02_IA_CC_live.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10crJTMrvALegJTScc2l1sAu2gjOVqUVL
"""

# 1. IMPORTAÇÕES
# 2. COLETA  DOS DADOS DA SÉRIE TEMPORAL
# 3. VISUALIZAÇÃO DA SÉRIE TEMPORAL
# 4. NORMALIZAÇÃO DOS DADOS
# 5. CRIAÇÃO DAS JANELAS TEMPORAIS
# 6. SEPARAÇÃO TREINO / TESTE (SEM EMBARALHAR)
# 7. CONSTRUÇÃO DO MODELO LSTM
# 8. TREINAMENTO DO MODELO
# 9. AVALIAÇÃO DO MODELO
# 10. VISUALIZAÇÃO DAS PREVISÕES
# 11. PREVISÃO DO PRÓXIMO DIA

# Importações
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.callbacks import EarlyStopping

from os import stat
# Coleta dos dados
ticker = "TSLA"
start_date = "2015-01-01" # aaaa-mm-dd
end_date = None # Data final == hoje

df = yf.download(ticker, start=start_date, end=end_date)
print()
print(df.head())
print(df.tail())

# Usar apenas o valor de fechamento 'Close'
series = df[['Close']].dropna()
print(series)

# Visualização da série temporal
plt.figure()
plt.plot(series)
plt.title(f"Preço de fechamento - {ticker}")
plt.xlabel("Data")
plt.ylabel("Preço")
plt.show()

# 4. NORMALIZAÇÃO DOS DADOS
scaler = MinMaxScaler(feature_range=(0, 1))
series_scaled = scaler.fit_transform(series.values)
print(series_scaled)

# 5. CRIAÇÃO DAS JANELAS TEMPORAIS
def create_windows(data, window_size):
  X, y = [], []
  for i in range(len(data) - window_size):
    X.append(data[i:i + window_size])
    y.append(data[i + window_size])
  return np.array(X), np.array(y)

window_size = 30 # 30 dias, pode mudar para verificar possíveis melhorias

X, y = create_windows(series_scaled, window_size)

print(f"Formato do X: {X.shape}")
print(f"Formato do y: {y.shape}")

# 6. SEPARAÇÃO TREINO / TESTE (SEM EMBARALHAR)
split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

print(f"Treino: {X_train.shape}")
print(f"Teste: {X_test.shape}")

# 7. CONSTRUÇÃO DO MODELO LSTM
model = Sequential()
model.add(LSTM(50, activation='tanh', input_shape=(window_size, 1)))
model.add(Dense(1))

model.compile(
    optimizer='adam',
    loss='mse'
)

model.summary()

# 8. TREINAMENTO DO MODELO
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    batch_size=32,
    epochs=50,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

# 9. Avaliação do modelo
y_pred = model.predict(X_test)

y_test_inv = scaler.inverse_transform(y_test)
y_pred_inv = scaler.inverse_transform(y_pred)

rmse = np.sqrt(mean_squared_error(y_test_inv, y_pred_inv))
print(f"RMSE: {rmse}")

# 10. Visualização das previsões
plt.figure()
plt.plot(series.index[-len(y_test):], y_test_inv, label="Valor real")
plt.plot(series.index[-len(y_test):], y_pred_inv, label="Valor previsto")
plt.title(f"Previsão do preço da ação {ticker} com LSTM")
plt.xlabel("Data")
plt.ylabel("Preço")
plt.legend()
plt.show()

# 11. Previsão de fechamento do próximo dia
last_window = series_scaled[-window_size:]
last_window = last_window.reshape(1, window_size, 1)

next_day_pred = model.predict(last_window) # valor entre 0 e 1
next_day_price = scaler.inverse_transform(next_day_pred) # valor previsto em dólares

print(f"Previsão de preço da {ticker} para o próximo dia: ${next_day_price[0][0]:.2f}")